language: java
jdk:
  - oraclejdk8
script:
  - ./gradlew check
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B
addons:
  apt:
    packages:
      - oracle-java8-installer
after_success:
  - bash <(curl -s https://codecov.io/bash)