language: java
jdk:
  - openjdk8
script:
  - apt-get update
  - apt-get install --no-install-recommends -y openjfx
  - ./gradlew check
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B
after_success:
  - bash <(curl -s https://codecov.io/bash)